### ISSUE TITLE
Give Projects and Activities a Due Date and Done Date

### ISSUE THREAD

**Issue by DaveHartley** [simonbaird/mGSD#11]
Feature
If you give Projects and Activities a Due Date and Done Date you can used the Due Date as a tickler insted of creating a Tickler Tiddler.  The new format for tiddlers would be.
'tiddler'  => 'New Tiddler',
'modified' => Time.now.convertToYYYYMMDDHHMM,
'created'  => Time.now.convertToYYYYMMDDHHMM,
'modifier' => 'YourName',
'tags'     => '',
'mgtd_done' => '',
'mgtd_due' => '',
'text'     => '',

**Comment by simonbaird** [comment]
Not sure about this since it's not really pure GTD. But I guess if it's optional then there's no harm supporting it. What about an easy/one click way to make a tickler for a project's due date? That might be useful.

**Comment by DaveHartley** [comment]
I made the modifications to dateChooserPlugin.js and TitleButtons.tiddler so that I could keep track of finished Projects.  Like so many of us I need to produce weekly and monthly reports of progress and this gave me the ability to dos so.  I also modified TiddlerViewMethods.js to support periodic reporting.  I am happy to share those changes if you are interested.
