### ISSUE TITLE
MGTD macro errors after deleting, saving to TiddlyWeb

### ISSUE THREAD

**Issue by edrex** [simonbaird/mGSD#15]
I've been testing mgtd using tiddlyweb to host, and I've found a fairly severe bug (which I believe has been reported before, link escapes me)

To set up a test environment:
1. Create account on http://hoster.peermore.com
2. Import "http://monkeygtd.tiddlyspot.com/downloadempty" into a new bag called "${username}.monkeygtd" (import action is represented by bent arrow icon next to bags heading)
3. Create a new recipe "${username}.gtdwiki" with the "system" and "${username}.monkeygtd" (system bag contains the plugins for saving to tiddlyweb)

To reproduce bug:
1. Delete a tiddler (tested with actions and projects, either using the red "x" or the delete link),
2. Click "save changes". 
3. The save works, but afterward MGTD macros fail with errors like
   
   ```
   Error while executing macro <<mgtdList>>:
   TypeError: Cannot call method 'matchesEvalExpr' of null
   ```

After reloading from the server, macros work again. It only seems to be triggered when a tiddler is deleted before saving.

**Comment by simonbaird** [comment]
This sounds familiar. I have a feeling someone has posted a fix for this problem. I will see if I can find it.

**Comment by edrex** [comment]
I've picked mGSD back up and I'm not experiencing this anymore. Closing.
