### ISSUE TITLE
Figure out (yet another) version numbering system

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/mGSD#2]
Git doesn't have revision numbers

**Comment by damo** [comment]
Just put version numbers in the branch names or tags. The choice would depend on how you intend to maintain older versions. For example, you could create a "b_v3" branch and just tag each minor version with "t_v3.1", "t_v3.2", etc. If you wanted to support maintenance of 3.1, you could create a maintenance branch "b_v3.1" from the version tag and then tag changes on that branch with "t_v3.1.1", "t_v3.1.2", etc.

**Comment by simonbaird** [comment]
Well I'm doing a manual version number now, starting at 3.1.0. And using tags. So hopefully things will work out okay. Closing.

**Comment by simonbaird** [comment]
Really closing.
