### ISSUE TITLE
Creating new future from a context does not work

### ISSUE THREAD

**Issue by sciolizer** [simonbaird/mGSD#27]
Steps to reproduce:
1. Under process tab, click "new context", and create a context "mycontext".
2. Click the "+" button next to Future, and create a task "mytask".

The mytask tiddler is empty - it does not contain context checkboxes, project/area/associated-contact/depends-on drop downs. a realm drop down, or any of the normal stuff that appears with a task. Additionally, the task does not even appear in the list of futures in the mycontext context.

The work around is to instead click the "+" button next to "Next" or "Waiting" on the mycontext tiddler, and then change the task to a future.

I am using Firefox 3.6.3.

**Comment by simonbaird** [comment]
Fixed in 3.1.7. Thanks very much for the report and the clear description.
