### ISSUE TITLE
No "Next Actions" in "Next and "Waiting Actions by Context" View

### ISSUE THREAD

**Issue by dlund4** [simonbaird/mGSD#30]
I do not see any "Next Actions" in the mGSD "Next and Waiting Actions
by Context" view. All I see are "Waiting" actions. I suspect there is
a bug in the code, but I am not sufficiently versed in tiddlywiki
javascript to fix it without investing a lot of time. Has anyone else
noticed this and created an issue? Can you please post the fix or a reference to a previous closed item addressing this?
Thanks.
Don,
Ypsilanti, MI

**Comment by simonbaird** [comment]
Closing, works for me?

**Comment by dlund4** [comment]
I apologize for not responding sooner. I was able to track down the issue by reviewing backups and discovered that when I tried incorporating the CheckboxPlugin it resulted in some kind of strange incompatibility issue. Certain characters in the 2 column javascript were being overwritten by a capital X, which of course caused problems interpreting the javascript. I could only see this by "edit"ing the two column dashboards so that I could see the javascript. So I just wanted to let you know so you could look at it if you wanted to and maybe pass it on to other users.

**Comment by simonbaird** [comment]
Cool, thanks for that.
