### ISSUE TITLE
Error in macro <<mgtdList>>

### ISSUE THREAD

**Issue by dlund4** [simonbaird/mGSD#31]
The mGSD "Next and Waiting Actions by Context Single Col" view shows
an "Error in macro <<mgtdList>>" at the top of the window. Can you tell me what that's all about and how to fix? Thanks.

**Comment by simonbaird** [comment]
Closing, works for me?

**Comment by jahagirdar** [comment]
I am seeing the same error after hitting upgrade today. Clicking on the text resulted in
1. Error while executing macro <<mgtdList>>:
2. ReferenceError: forceReflow is not defined
