### ISSUE TITLE
Rendering problem for tiddlers with square brackets in the content

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/mGSD#8]
Heller 26-Oct-2009:
"Yep the problem is still there, all you have to do is open say the
waiting action
'Storage request form' edit it putting
[ ] Hello world
into the notes area and save and then the note icon no longer renders
on the dashboard"

**Comment by damo** [comment]
I get this problem, too. It took me a while to figure out what the problem was. The square brackets only cause a problem when used as the tooltip for the notes icon; they are OK when the tiddler content is displayed normally.

**Comment by simonbaird** [comment]
Fixed in 3.1.0.
